### ISSUE TITLE
What Python version should I use?

### ISSUE THREAD

**Issue by ElyosOfTheAbyss** [darcycartwright/PokemonGO#1]
When I try to use it, it keeps giving me "invalid syntax"

`\PokemonGO-master>pokedex.py
  File "C:\Users\User\Desktop\PokemonGO-master\pokedex.py", line 76
    yield from client.send_file(message.channel, '/Users/darcycartwright/Development/Python/Pokedex Bot/images/large/{0:0>3}.png'.format(_number), filename='{0:0>3}.png'.format(_number))
             ^
SyntaxError: invalid syntax
`
I  think it might be because I might have a wrong pythin version. Which one are you using?

**Comment by darcycartwright** [comment]
If you upgrade to Python 3+ it should work.

**Comment by darcycartwright** [comment]
You also need to upgrade to the latest version of discord.py as a lot of the primary commands changed.

**Comment by darcycartwright** [comment]
Depending on which version of python you may or may not be able to use .format().

I'd recommend updating to the latest version of python (including the discord and sqlite3 modules) and give it another go.
